### ISSUE TITLE
Docker Image Security tips?

### ISSUE THREAD

**Issue by lirantal** [eon01/DockerCheatSheet#15]
Hi Aymen,

I'm wondering if you'd want to also include a security part with some tips we mentioned about docker images in https://snyk.io/blog/10-docker-image-security-best-practices/ ?

**Comment by eon01** [comment]
Hi @lirantal , sorry for my late reply. Yes, good idea! Would you like to submit a PR including this?

**Comment by lirantal** [comment]
Definitely! got it here: https://github.com/eon01/DockerCheatSheet/pull/16
