### ISSUE TITLE
Missing words

### ISSUE THREAD

**Issue by ghost** [eon01/DockerCheatSheet#17]
https://github.com/eon01/DockerCheatSheet#exposing-ports

> Using Dockerfile, you can expose a port on the container using:
>
>`EXPOSE <port_number>`
>
>**You can also map the container port to a host port using:**
>
>e.g.
>
>`docker run -p $HOST_PORT:$CONTAINER_PORT --name infinite -t infinite`

Map container port to host using what?

**Comment by eon01** [comment]
thanks, fixed.
